apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    helm.sh/chart: {{ include "nginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "nginx.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      - name: mount
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "mkdir /usr/share/nginx/html;touch /usr/share/nginx/html/index.html;chown -R nginx /usr/share/nginx/html"]
        volumeMounts:
        - name: {{ include "nginx.name" . }}
          mountPath: /usr/share/nginx
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: {{ include "nginx.name" . }}
          mountPath: /usr/share/nginx
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        {{- if .Values.resources }}
        resources: 
        {{- toYaml .Values.resources | nindent 8 }}
        {{- end }}
        {{- if .Values.nodeSelector }}
          nodeSelector:
      {{- toYaml .Values.resources | nindent 4 }}
      {{- end }}
        {{- if .Values.affinity}}
          affinity:
    {{- toYaml .Values.affinity  | nindent 4 }}
    {{- end }}
    {{- if .Values.tolerations }}
          tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
    {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "nginx.name" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.className }}
      resources:
        requests:
          storage: {{ .Values.storage.size }}
