apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.fullname }}
  namespace: {{ .Values.namespace }}
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.0
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
