apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namepace }}
  labels:
    heritage: "Tiller"
    release: "RELEASE-NAME"
    chart: provisioner-2.3.0
