kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsprov-nfsprov-0
  #annotations:
  #  volume.beta.kubernetes.io/storage-class: "example-nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
