# Default values for dse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: default
resources:
  cpu: 2
  mem: 2Gi 

image:
  repository: datastax/dse-server
  tag: 6.7.0
  pullPolicy: IfNotPresent

stress:
  records: "10000000"
  ops: ops(insert=1) #insert only workload single item "batch"
  contactpods:
    - mydse-datastax-dse-0
    - mydse-datastax-dse-1
  contactservice: mydse-datastax-dse
  stressYaml: |
    #heavily sourced from https://www.instaclustr.com/deep-diving-cassandra-stress-part-3-using-yaml-profiles/
    keyspace: mystress
    keyspace_definition: |
      CREATE KEYSPACE mystress WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '3'};
    
    table: time_series
    table_definition: |
      CREATE TABLE time_series(
            machine_id uuid,
            bucket bigint,
            ts timestamp,
            metric double,
            log text,
            PRIMARY KEY ((machine_id, bucket), ts)
        )
    #
    # Meta information for generating data
    #
    columnspec:
      - name: host
        size: fixed(32) 
        population: uniform(1..600) 
      - name: bucket_time
        cluster: fixed(18)
        population: uniform(1..4000)
      - name: ts
        cluster: fixed(15)
      - name: log 
        size: gaussian(100..10000)
    
    insert:
      partitions: fixed(1)      # 1 partition per batch
      batchtype: UNLOGGED       # use unlogged batches
      select: fixed(10)/10      # no chance of skipping a row when generating inserts
     
    #
    # Read queries to run against the schema
    #
    queries:
       pull-for-rollup:
          cql: select * from time_series where machine_id = ? and bucket = ?
          fields: samerow             # pick selection values from same row in partition
       get-a-value:
          cql: select * from time_series where machine_id = ? and bucket = ? and ts = ?
          fields: samerow             #
