kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: leader-locking-{{ include "nfsprov.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nfsprov.fullname" . }}
    # replace with namespace where provisioner is deployed
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: leader-locking-{{ include "nfsprov.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
