kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "nfsprov.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "nfsprov.fullname" . }}
    helm.sh/chart: {{ include "nfsprov.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nfsprov.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  serviceName: {{ include "nfsprov.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nfsprov.fullname" . }}
        helm.sh/chart: {{ include "nfsprov.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
    {{ toYaml . | indent 4 }}
      {{- end }}
      serviceAccount: {{ include "nfsprov.fullname" . }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: nfs-provisioner
          image: quay.io/kubernetes_incubator/nfs-provisioner:latest
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
            - name: rpcbind-udp
              containerPort: 111
              protocol: UDP
          securityContext:
            capabilities:
              add:
                - DAC_READ_SEARCH
                - SYS_RESOURCE
          args:
            - "-provisioner=example.com/nfs"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SERVICE_NAME
              value: {{ include "nfsprov.fullname" . }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: {{ include "nfsprov.fullname" . }}
              mountPath: /export
  volumeClaimTemplates:
  - metadata:
      name: {{ include "nfsprov.fullname" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.storage.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.storage.data.size }}
